name: Deploy to Web Server

on:
  push:
    branches: [ main ]  # Trigger when changes are pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    #- name: FTP
    #  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    #  with:
    #    server: ${{ secrets.FTP_SERVER }}
    #    username: ${{ secrets.FTP_USERNAME }}
    #    password: ${{ secrets.FTP_PASSWORD }}
    #    local-dir: ./path/to/files/  # Directory containing files to copy
    #    server-dir: /path/on/webserver/  # Destination on the web server

    #OR
    #- name: SSH
    #  uses: appleboy/ssh-action@master
    #  with:
    #    host: ${{ secrets.SSH_HOST }}
    #    username: ${{ secrets.SSH_USERNAME }}
    #    key: ${{ secrets.SSH_PRIVATE_KEY }}
    #    script: |
    #      cd /path/on/server
    #      rsync -av /path/to/source/ /path/to/destination/
    
    #OR
    #- name: S3
    #  uses: jakejarvis/s3-sync-action@master
    #  with:
    #    args: --acl public-read --follow-symlinks --delete
    #  env:
    #    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #    SOURCE_DIR: 'path/to/files'
